name: CTest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test
      run: |
        cmake -S . -B build
        cd build
        make 
        ctest
